### ISSUE TITLE
Preferred google Drive link for weights file

### ISSUE THREAD

**Issue by hvgazula** [gaiborjosue/trained-models-fork#61]
Here are two links for the same file. Which one's the preferred one for adding a model?

link when I right click the file and select 'copy link': https://drive.google.com/file/d/18KdBZLwd-8ld3SZoQCXAXwvrCtdeABU-/view?usp=drive_link

link when I double click on the file: https://drive.google.com/drive/u/2/folders/1i5aTpSGbFi6K4t3IqKr9pctljVdEpEx0

**Comment by gaiborjosue** [comment]
Hello @hvgazula the preferred way is: Right click > Share > Edit Permissions > Anyone with the link as editor > Copy link

Then you would have to extract the ID to this URL>

"https://drive.google.com/uc?id=ID OF THE FILE&confirm=t"

**Comment by hvgazula** [comment]
Does the user have to do that?

**Comment by gaiborjosue** [comment]
Yes. Because we need a direct download URL.

I will also add steps on how to do this in the docs.

**Comment by hvgazula** [comment]
Thank. For the records, in this case it would be 
https://drive.google.com/uc?id=18KdBZLwd-8ld3SZoQCXAXwvrCtdeABU-&confirm=t
