### ISSUE TITLE
Model's card and spec

### ISSUE THREAD

**Issue by hvgazula** [gaiborjosue/trained-models-fork#63]
>  Please provide a URL for your model_card.yaml and model_spec.yaml files.

We should include a link to creating these files here itself. For example-

>  Please provide a URL for your model_card.yaml and model_spec.yaml files. For info on creating these files, please see [link here](url)

What do you think?

**Comment by gaiborjosue** [comment]
I agree 👍

**Comment by hvgazula** [comment]
Can I use the DeepCSR spec.yaml to create the spec for PialNN? Please point me to any docs so I can create the spec for PialNN and procced with testing.

**Comment by hvgazula** [comment]
Also, is the spec.yaml optional as I don't see an asterisk in this field?

**Comment by gaiborjosue** [comment]
yes you can use deepcsr spec, spec.yaml is not used at all other than validation. So there should be no problem for testing.

**Comment by gaiborjosue** [comment]
The spec.yaml is not optional I will make it required.
