### ISSUE TITLE
Zip issues

### ISSUE THREAD

**Issue by gaiborjosue** [gaiborjosue/trained-models-fork#65]
Hello @hvgazula I am testing the zip right now with deepcsr. And I get this error:

https://github.com/gaiborjosue/trained-models-fork/actions/runs/6511766055/job/17688329367#step:11:25

![image](https://github.com/gaiborjosue/trained-models-fork/assets/78832141/171657af-a362-4971-9a77-e7dacc2e4b5e)

That happens when trying to use the test command after extracting the zip.

**Comment by hvgazula** [comment]
Should I close this?

**Comment by gaiborjosue** [comment]
Yes.
