### ISSUE TITLE
confirm actions/checkout@ version

### ISSUE THREAD

**Issue by hvgazula** [gaiborjosue/trained-models-fork#80]
https://github.com/gaiborjosue/trained-models-fork/actions/runs/6711265662/workflow

I just noticed you have both v3 and v4 at different places. Any specific reason?

**Comment by gaiborjosue** [comment]
Hello @hvgazula, no specific reason. I was just debugging and thought it was due to the checkout version.

**Comment by hvgazula** [comment]
I only meant you should change everything to v4 and test while you are at it. Different versions at different locations for the same action could be very confusing.
